version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      java: openjdk8
    #commands:
      # - command
      # - command
    finally:
      - echo Install complete
  build:
    commands:
      - mvn install
    finally:
      - echo Build complete
  post_build:
    commands:
      - mvn verify -Dregion=us-east-2
    finally:
      - echo Verification complete
reports:
  unit-tests:
    files:
      - "**/*"
    base-directory: 'target/surefire-reports/'
    file-format: JunitXml
    discard-paths: no
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
