
name: Java CI with Maven

on:
  push:
    branches: [ v1.x ]
  pull_request:
    branches: [ v1.x ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix :
        os: [ubuntu-latest, windows-latest]
        java: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml -D region=us-east-1
