# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix : 
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::264319671630:role/GitHubActionsOidc
    - name: Build with Maven
      run: |
        GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)
        mvn -B package --file pom.xml -D region=us-east-2 -D ledgerSuffix=-${{ strategy.job-index }}-$GITHUB_SHA_SHORT
      shell: bash
    - name: Upload code coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      shell: bash
